config/routes.rb
Rails.application.routes.draw do
  resources :selected_times
  resources :possible_days
  resources :events do
  	get 'timetable'
  end
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :possible_days
	has_many :selected_times
	has_many :students

	accepts_nested_attributes_for :possible_days
	accepts_nested_attributes_for :selected_times, allow_destroy: true
	accepts_nested_attributes_for :students, allow_destroy: true
end

app/models/possible_day.rb
class PossibleDay < ApplicationRecord
  belongs_to :event, optional: true
end

app/models/selected_time.rb
class SelectedTime < ApplicationRecord
  belongs_to :student
  belongs_to :event
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @name = params[:name];
    @event = Event.new
    @event.possible_days.build
    
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    
    render :timetable
    # respond_to do |format|
    #   if @event.save
    #     format.html { redirect_to @event, notice: 'Event was successfully created.' }
    #     format.json { render :show, status: :created, location: @event }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @event.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def timetable
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:type, :lecture_title, :description, :email, :nb_of_times, :duration, :link_1, :link_2, possible_days_attributes: [:day,:from_time,:to_time,:_destroy])
    end
end

app/controllers/possible_days_controller.rb
class PossibleDaysController < ApplicationController
  before_action :set_possible_day, only: [:show, :edit, :update, :destroy]

  # GET /possible_days
  # GET /possible_days.json
  def index
    @possible_days = PossibleDay.all
  end

  # GET /possible_days/1
  # GET /possible_days/1.json
  def show
  end

  # GET /possible_days/new
  def new
    @possible_day = PossibleDay.new
  end

  # GET /possible_days/1/edit
  def edit
  end

  # POST /possible_days
  # POST /possible_days.json
  def create
    @possible_day = PossibleDay.new(possible_day_params)

    respond_to do |format|
      if @possible_day.save
        format.html { redirect_to @possible_day, notice: 'Possible day was successfully created.' }
        format.json { render :show, status: :created, location: @possible_day }
      else
        format.html { render :new }
        format.json { render json: @possible_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /possible_days/1
  # PATCH/PUT /possible_days/1.json
  def update
    respond_to do |format|
      if @possible_day.update(possible_day_params)
        format.html { redirect_to @possible_day, notice: 'Possible day was successfully updated.' }
        format.json { render :show, status: :ok, location: @possible_day }
      else
        format.html { render :edit }
        format.json { render json: @possible_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /possible_days/1
  # DELETE /possible_days/1.json
  def destroy
    @possible_day.destroy
    respond_to do |format|
      format.html { redirect_to possible_days_url, notice: 'Possible day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_possible_day
      @possible_day = PossibleDay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def possible_day_params
      params.require(:possible_day).permit(:day, :from_date, :to_date, :from_time, :to_time, :event_id)
    end
end

app/controllers/selected_times_controller.rb
class SelectedTimesController < ApplicationController
  before_action :set_selected_time, only: [:show, :edit, :update, :destroy]

  # GET /selected_times
  # GET /selected_times.json
  def index
    @selected_times = SelectedTime.all
  end

  # GET /selected_times/1
  # GET /selected_times/1.json
  def show
  end

  # GET /selected_times/new
  def new
    @selected_time = SelectedTime.new
  end

  # GET /selected_times/1/edit
  def edit
  end

  # POST /selected_times
  # POST /selected_times.json
  def create
    @selected_time = SelectedTime.new(selected_time_params)

    respond_to do |format|
      if @selected_time.save
        format.html { redirect_to @selected_time, notice: 'Selected time was successfully created.' }
        format.json { render :show, status: :created, location: @selected_time }
      else
        format.html { render :new }
        format.json { render json: @selected_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selected_times/1
  # PATCH/PUT /selected_times/1.json
  def update
    respond_to do |format|
      if @selected_time.update(selected_time_params)
        format.html { redirect_to @selected_time, notice: 'Selected time was successfully updated.' }
        format.json { render :show, status: :ok, location: @selected_time }
      else
        format.html { render :edit }
        format.json { render json: @selected_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selected_times/1
  # DELETE /selected_times/1.json
  def destroy
    @selected_time.destroy
    respond_to do |format|
      format.html { redirect_to selected_times_url, notice: 'Selected time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selected_time
      @selected_time = SelectedTime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selected_time_params
      params.require(:selected_time).permit(:student_id, :event_id, :from_date, :to_date, :from_time, :to_time, :cell_status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/possible_days_helper.rb
module PossibleDaysHelper
end

app/helpers/selected_times_helper.rb
module SelectedTimesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3 style="padding-left: 3%;"> Schedule <%= @name %> </h3> 

  <div class="field" style="padding-left: 3%;">
    <%= f.label :event_title %>
    <%= f.text_field :lecture_title %>
  </div>

  <div class="field" style="padding-left: 3%;">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field" style="padding-left: 3%;">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field" style="padding-left: 3%;">
    <%= f.label :number_of_times_per_week %>
    <%= f.select :nb_of_times, options_for_select(['1', '2','3','4','5','6','7']), {} %>
  </div>

  <div class="field" style="padding-left: 3%;">
    <%= f.label :duration %>
    <%= f.select :nb_of_times, options_for_select(['1:00', '1:30','2:00','2:30','3:00','3:30','4:00']), {} %>
     Hours
  </div>
  
  <%= f.nested_fields_for :possible_days do |ff| %>
    <%= render partial: 'events/partials/days', locals: {ff: ff} %>
  <% end %>
  <div class="field" style="padding-left: 3%;">
    <%= f.add_nested_fields_link :possible_days  %>
  </div>

  <div class="actions" style="padding-left: 3%;">
    <%= f.submit "Next" %>
  </div>
<% end %>


<script>

  $(document).ready(function(){
    $(document).on('change','#event_nb_of_times',function(){
    var startDate = $('#event_nb_of_times').val();
    var i=0;
    for(i=0;i<startDate;i++)
    {
      $('.add_nested_fields_link').click();
    }

    });
    
  });

</script>
  

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<!-- <p id="notice"><%#= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Lecture title</th>
      <th>Description</th>
      <th>Email</th>
      <th>Nb of times</th>
      <th>Duration</th>
      <th>Link 1</th>
      <th>Link 2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <#% @events.each do |event| %>
      <tr>
        <td><%#= event.type %></td>
        <td><%#= event.lecture_title %></td>
        <td><%#= event.description %></td>
        <td><%#= event.email %></td>
        <td><%#= event.nb_of_times %></td>
        <td><%#= event.duration %></td>
        <td><%#= event.link_1 %></td>
        <td><%#= event.link_2 %></td>
        <td><%#= link_to 'Show', event %></td>
        <td><%#= link_to 'Edit', edit_event_path(event) %></td>
        <td><%#= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <#% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Event', new_event_path %> -->
<div class="container">
  <div style="margin-left:10%;margin-top:3%;border: 2px solid black;">
    
      <h1  style="background-color: blue; color: white;margin-top: 0; padding-bottom: 5%; padding-top: 3%; padding-left: 3%;"> <strong>Academic Event Scheduler</strong> </h1>
      
    <%= link_to 'Schedule a Lecture', new_event_path(name: "Lecture"), class: "landing-page-button" %>
    <%= link_to 'Schedule an Exam', new_event_path(name: "Exam"), class: "landing-page-button"  %>
      
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div style="margin-left:10%;margin-top:3%;border: 2px solid black; ">
    
      <h1  style="background-color: blue; color: white;margin-top: 0; padding-bottom: 5%; padding-top: 3%; padding-left: 3%;"> <strong>Academic Event Scheduler</strong> </h1>

	  <%= render 'form', event: @event %>
	</div>
</div>

app/views/events/partials/_day_time.html.erb
		<div class="col-md-2" style="background-color: blue;border: 1px solid white;color:white;">
			<%= time %>
		</div>
		<div class="col-md-1" style="background-color: gray;border: 1px solid white;">
			.
		</div>
		<div class="col-md-1" style="background-color: gray;border: 1px solid white;">
			.
		</div>
		<div class="col-md-1" style="background-color: gray;border: 1px solid white;">
			.
		</div>
		<div class="col-md-1" style="background-color: gray;border: 1px solid white;">
			.
		</div>
		<div class="col-md-1" style="background-color: gray;border: 1px solid white;">
			.
		</div>
		<div class="col-md-1" style="background-color: gray;border: 1px solid white;">
			.
		</div>
		<div class="col-md-1" style="background-color: gray;border: 1px solid white;">
			.
		</div>

app/views/events/partials/_days.html.erb
 <div class="field" style="padding-left: 3%;">
    <%= ff.label :day %>
    <%= ff.select :day, options_for_select(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']) %>
</div>
<div class="field" style="padding-left: 3%;">
    <%= ff.label :from_time %>
    <%= ff.select :from_time, options_for_select(['8:00 A.M','8:30 A.M','9:00 A.M','9:30 A.M','10:00 A.M','10:30 A.M','11:00 A.M','11:30 A.M','12:00 P.M', '12:30 P.M', '1:00 P.M','1:30 P.M','2:00 P.M','2:30 P.M','3:00 P.M','3:30 P.M', '4:00 P.M', '4:30 P.M' ]) %>
</div>
<div class="field" style="padding-left: 3%;">
    <%= ff.label :to_time %>
    <%= ff.select :to_time, options_for_select(['8:30 A.M','9:00 A.M','9:30 A.M','10:00 A.M','10:30 A.M','11:00 A.M','11:30 A.M','12:00 P.M', '12:30 P.M', '1:00 P.M','1:30 P.M','2:00 P.M','2:30 P.M','3:00 P.M','3:30 P.M', '4:00 P.M', '4:30 P.M','5:00 P.M' ]) %>
</div>
<div class="field" style="padding-left: 3%;">
    <%= ff.remove_nested_fields_link 'Remove me' %>
</div> 

app/views/events/shows.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @event.type %>
</p>

<p>
  <strong>Lecture title:</strong>
  <%= @event.lecture_title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Email:</strong>
  <%= @event.email %>
</p>

<p>
  <strong>Nb of times:</strong>
  <%= @event.nb_of_times %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @event.duration %>
</p>

<p>
  <strong>Link 1:</strong>
  <%= @event.link_1 %>
</p>

<p>
  <strong>Link 2:</strong>
  <%= @event.link_2 %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/timetable.html.erb
<div class="container">
  <div style="margin-left:10%;margin-top:3%; ">
	  <h1  style="background-color: blue; color: white;margin-top: 0; padding-bottom: 5%; padding-top: 3%; padding-left: 3%;"> <strong>Academic Event Scheduler</strong> </h1>
	  <div style="margin-left: 5%">
	  	<h3> Lectures Table </h3>
	  
		  <div class="row">
			<div class="col-md-2" style="background-color: blue;border: 1px solid white;color:white;">
				Time/Day
			</div>
			<div class="col-md-1" style="background-color: blue;border: 1px solid white;color:white;">
				Sunday
			</div>
			<div class="col-md-1" style="background-color: blue;border: 1px solid white;color:white;">
				Monday
			</div>
			<div class="col-md-1" style="background-color: blue;border: 1px solid white;color:white;">
				Tuesday
			</div>
			<div class="col-md-1" style="background-color: blue;border: 1px solid white;color:white;">
				Wednesday
			</div>
			<div class="col-md-1" style="background-color: blue;border: 1px solid white;color:white;">
				Thursday
			</div>
			<div class="col-md-1" style="background-color: blue;border: 1px solid white;color:white;">
				Friday
			</div>
			<div class="col-md-1" style="background-color: blue;border: 1px solid white;color:white;">
				Saturday
			</div>
		  </div>

		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '08-00 - 08:30 am'} %>
		  </div>
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '08:30 - 09:00 am'} %>		
		  </div> 
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '09:00 - 09:30 am'} %>		
		  </div> 
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '09:30 - 10:00 am'} %>		
		  </div> 	 
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '10:00 - 10:30 am'} %>		
		  </div> 
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '10:30 - 11:00 am'} %>		
		  </div> 
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '11:00 - 11:30 am'} %>		
		  </div> 
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '11:30 - 12:00 pm'} %>		
		  </div> 
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '12:00 - 12:30 pm'} %>		
		  </div>	 

		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '12:30 - 01:00 pm'} %>		
		  </div> 
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '01:00 - 01:30 pm'} %>		
		  </div>
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '01:30 - 02:00 pm'} %>		
		  </div> 
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '02:00 - 02:30 pm'} %>		
		  </div>
		  <div class="row">
		    <%= render partial: 'events/partials/day_time', locals: {time: '02:30 - 03:00 pm'} %>		
		  </div> 
		  <br>
		  <div class="row">
			<div class="col-md-3" style="border: 1px solid white;">
				
			</div>	
			<div class="col-md-1" style="border: 1px solid white;background-color: gray;">
				.
			</div>
			<div class="col-md-1" style="border: 1px solid white;">
				Available
			</div>
			<div class="col-md-1" style="border: 1px solid white;">
				
			</div>
			<div class="col-md-1" style="border: 1px solid white;background-color: pink;">
				.
			</div>
			<div class="col-md-2" style="border: 1px solid white;">
				Not Available
			</div>	 	    		
		  </div> 	  
	  </div>
	  <%= recaptcha_tags %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Academic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/possible_days/_form.html.erb
<%= form_for(possible_day) do |f| %>
  <% if possible_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(possible_day.errors.count, "error") %> prohibited this possible_day from being saved:</h2>

      <ul>
      <% possible_day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %>
    <%= f.text_field :day %>
  </div>

  <div class="field">
    <%= f.label :from_date %>
    <%= f.date_select :from_date %>
  </div>

  <div class="field">
    <%= f.label :to_date %>
    <%= f.date_select :to_date %>
  </div>

  <div class="field">
    <%= f.label :from_time %>
    <%= f.datetime_select :from_time %>
  </div>

  <div class="field">
    <%= f.label :to_time %>
    <%= f.datetime_select :to_time %>
  </div>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.text_field :event_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/possible_days/edit.html.erb
<h1>Editing Possible Day</h1>

<%= render 'form', possible_day: @possible_day %>

<%= link_to 'Show', @possible_day %> |
<%= link_to 'Back', possible_days_path %>

app/views/possible_days/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Possible Days</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>From date</th>
      <th>To date</th>
      <th>From time</th>
      <th>To time</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @possible_days.each do |possible_day| %>
      <tr>
        <td><%= possible_day.day %></td>
        <td><%= possible_day.from_date %></td>
        <td><%= possible_day.to_date %></td>
        <td><%= possible_day.from_time %></td>
        <td><%= possible_day.to_time %></td>
        <td><%= possible_day.event %></td>
        <td><%= link_to 'Show', possible_day %></td>
        <td><%= link_to 'Edit', edit_possible_day_path(possible_day) %></td>
        <td><%= link_to 'Destroy', possible_day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Possible Day', new_possible_day_path %>

app/views/possible_days/new.html.erb
<h1>New Possible Day</h1>

<%= render 'form', possible_day: @possible_day %>

<%= link_to 'Back', possible_days_path %>

app/views/possible_days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @possible_day.day %>
</p>

<p>
  <strong>From date:</strong>
  <%= @possible_day.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @possible_day.to_date %>
</p>

<p>
  <strong>From time:</strong>
  <%= @possible_day.from_time %>
</p>

<p>
  <strong>To time:</strong>
  <%= @possible_day.to_time %>
</p>

<p>
  <strong>Event:</strong>
  <%= @possible_day.event %>
</p>

<%= link_to 'Edit', edit_possible_day_path(@possible_day) %> |
<%= link_to 'Back', possible_days_path %>

app/views/selected_times/_form.html.erb
<%= form_for(selected_time) do |f| %>
  <% if selected_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(selected_time.errors.count, "error") %> prohibited this selected_time from being saved:</h2>

      <ul>
      <% selected_time.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %>
    <%= f.text_field :student_id %>
  </div>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.text_field :event_id %>
  </div>

  <div class="field">
    <%= f.label :from_date %>
    <%= f.date_select :from_date %>
  </div>

  <div class="field">
    <%= f.label :to_date %>
    <%= f.date_select :to_date %>
  </div>

  <div class="field">
    <%= f.label :from_time %>
    <%= f.datetime_select :from_time %>
  </div>

  <div class="field">
    <%= f.label :to_time %>
    <%= f.datetime_select :to_time %>
  </div>

  <div class="field">
    <%= f.label :cell_status %>
    <%= f.check_box :cell_status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/selected_times/edit.html.erb
<h1>Editing Selected Time</h1>

<%= render 'form', selected_time: @selected_time %>

<%= link_to 'Show', @selected_time %> |
<%= link_to 'Back', selected_times_path %>

app/views/selected_times/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Selected Times</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Event</th>
      <th>From date</th>
      <th>To date</th>
      <th>From time</th>
      <th>To time</th>
      <th>Cell status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @selected_times.each do |selected_time| %>
      <tr>
        <td><%= selected_time.student %></td>
        <td><%= selected_time.event %></td>
        <td><%= selected_time.from_date %></td>
        <td><%= selected_time.to_date %></td>
        <td><%= selected_time.from_time %></td>
        <td><%= selected_time.to_time %></td>
        <td><%= selected_time.cell_status %></td>
        <td><%= link_to 'Show', selected_time %></td>
        <td><%= link_to 'Edit', edit_selected_time_path(selected_time) %></td>
        <td><%= link_to 'Destroy', selected_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Selected Time', new_selected_time_path %>

app/views/selected_times/new.html.erb
<h1>New Selected Time</h1>

<%= render 'form', selected_time: @selected_time %>

<%= link_to 'Back', selected_times_path %>

app/views/selected_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @selected_time.student %>
</p>

<p>
  <strong>Event:</strong>
  <%= @selected_time.event %>
</p>

<p>
  <strong>From date:</strong>
  <%= @selected_time.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @selected_time.to_date %>
</p>

<p>
  <strong>From time:</strong>
  <%= @selected_time.from_time %>
</p>

<p>
  <strong>To time:</strong>
  <%= @selected_time.to_time %>
</p>

<p>
  <strong>Cell status:</strong>
  <%= @selected_time.cell_status %>
</p>

<%= link_to 'Edit', edit_selected_time_path(@selected_time) %> |
<%= link_to 'Back', selected_times_path %>